<?php
include_once $_SERVER["DOCUMENT_ROOT"] . "/api/base.model.php";

class ChatItem extends ModelItem
{
   public $id;
   public $eventId;
   public $senderId;
   public $timestamp;
   public $deleted;
   public $toAll;
   public $text;
   public $subjectType;
   public $subjectId;
}

class Chat extends BaseModel
{
   public $tableName = "chat";
   public $modelItem = "ChatItem";

   public function getListAction($where = null, $order = null)
   {
      if (!$where) {
         $where = array();
         If (isset($_REQUEST["subjectId"])) $where["subjectId"] = $_REQUEST["subjectId"];
         If (isset($_REQUEST["subjectType"])) $where["subjectType"] = $_REQUEST["subjectType"];
      }
      if (!$order) $order=array("timestamp"=> "DESC");
      return parent::getListAction($where, $order); // TODO: Change the autogenerated stub
   }
   public function sqlBuildGetAllItems($where = null, $order = null)
   {
      $cmd = 'SELECT a.*, b.fullName as senderName  FROM `' . $this->tableName . '` a
       INNER JOIN users b ON b.id = a.senderId';
      if (isset($where)) $cmd .= $this->sqlBuildWhere($where);
      if (isset($order)) $cmd .= $this->sqlBuildOrder($order);
      return $cmd;
   }

}
